---
title: "Lab 2: Introduction to R"
output: html_notebook
---

## 2.3.1 Basic Commands

### Concantenate

```{r}

x <- c(1,3,4,5)
x
```

```{r}
x = c(1,5,6)
x
y = c(1,3,5)
y
```
### length

```{r}

length(x)

length(y)

x+y

```
### List of the objects

```{r}

ls()

```
```{r}
rm(x,y)
```


```{r}
ls()
```

```{r}
### romove all the objects at once

rm(list=ls())

```

### Matrix

```{r}
x= matrix(data=c(1,3,4,5), nrow=2, ncol=2)
x
```

```{r}
x = matrix(c(23,412,4,5),2,2)
x
```
```{r}
matrix(c(1,2,3,4),2,2, byrow=TRUE)
```
### Matrix operations

```{r}

sqrt(x)
```


```{r}
x^2
```

```{r}
x = rnorm(50)
y = x +rnorm(50, mean = 50, sd = 1)
cor(x,y)
```
### setting the seed()

```{r}

set.seed(1303)
rnorm(50)

```
```{r}

set.seed(3)
y = rnorm(100)
mean(y)
var(y)
sqrt(var(y))
sd(y)
```

## 2.3.2 Graphics

```{r}
x=rnorm (100)
y=rnorm (100)
plot(x,y)
plot(x,y,xlab=" this is the x-axis",ylab=" this is the y-axis",
main=" Plot of X vs Y")
```

### exporting to pdf

```{r}
pdf (" Figure .pdf ")
plot(x,y,col =" green ")
dev.off ()

```
### Creating a secuence

```{r}

x=seq (1 ,10)
x
x=1:10
x

```

### Plotting a contour

```{r}

y=x
f=outer(x,y,function (x,y)cos(y)/(1+x^2))
contour (x,y,f)
contour (x,y,f,nlevels =45, add=T)
fa=(f-t(f))/2
contour (x,y,fa,nlevels =15)

```

```{r}

image(x,y,fa)
persp(x,y,fa)
persp(x,y,fa ,theta =30)
persp(x,y,fa ,theta =30, phi =20)
persp(x,y,fa ,theta =30, phi =70)
persp(x,y,fa ,theta =30, phi =40)

```

## 2.3.3 Indexing Data

```{r}

A=matrix (1:16 ,4 ,4)
A

```
### Defininf a matrix

```{r}
A[c(1,3) ,c(2,4) ]
A

A[1:3 ,2:4]
A

A[1:3 ,2:4]
A

A[ ,1:2]
A
```
### Showing an entire row

```{r}
A[1,]
```

### Showing just some rows

```{r}
A[-c(1,3) ,]
```

```{r}
dim(A)
```
## 2.3.4 Loading Data

```{r}
data("mtcars")
```


```{r}
attach(mtcars)
dim(mtcars)
```
```{r}
names(mtcars)
```

## 2.3.5 Additional Graphical and Numerical Summaries

```{r}
plot(cyl , mpg)
```

```{r}
cyl =as.factor(cyl)
```

```{r}
plot(cyl , mpg)
plot(cyl , mpg , col ="red ")
plot(cyl , mpg , col ="red", varwidth =T)
plot(cyl , mpg , col ="red", varwidth =T,horizontal =T)
plot(cyl , mpg , col ="red", varwidth =T, xlab=" cyl ",
ylab ="MPG ")
```

```{r}
hist(mpg)
hist(mpg ,col =2)
hist(mpg ,col =2, breaks =15)
```

```{r}
pairs(mtcars)
pairs(∼ mpg + disp + hp)
```
```{r}
plot(hp ,mpg)
identify (hp ,mpg)
```
```{r}
summary(hp)
```

